It's unnecessary to specify the character as UTF-8 in all examples
openid/sse pull request #10
Opened 2022-06-06 22:37 UTC by adeinega

It's a default encoding for JSON. Furthermore, the specification tells us

> A successful response MUST use the 200 OK HTTP status code and return a JSON object using the "application/json" content.

2022-06-28 15:53 UTC, timcappalli approved these changes
lgtm

2022-08-09 17:03 UTC, FragLegs requested changes
Needs to be copied to the txt and html files as well. See README for running the converter

2022-08-09 19:48 UTC, adeinega commented
@FragLegs, done.

2022-08-11 18:40 UTC, FragLegs approved these changes

2022-09-11 22:23 UTC, merged