Fix some typos
openid/sse pull request #12
Opened 2022-06-06 23:01 UTC by adeinega

2022-06-28 15:47 UTC, timcappalli approved these changes
lgtm

2022-08-09 17:01 UTC, FragLegs requested changes
Needs to be copied to the txt and html files as well

2022-08-09 19:56 UTC, adeinega commented
@FragLegs, done.

2022-08-11 18:39 UTC, FragLegs approved these changes
looks good

2022-09-11 22:24 UTC, tulshi approved these changes

2022-09-11 22:24 UTC, merged